server:
  port: 6002
spring:
  application:
    name: clouddo-zuul

#zuul
zuul:
  prefix: /qbl
  ignored-services: clouddo-provider-hystrix     #真实服务名忽略    "*"
  routes:
    mydept.serviceId: clouddo-provider-hystrix    #域名映射
    mydept.path: /mydept/**

#eureka 配置
eureka:
  client:                                         #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/   #单机
  instance:
    instance-id: zuul-9527.com    #hystrix服务器名
    prefer-ip-address: true                       #访问路径可以显示IP地址
info:
  app.name: cxk-microservicecloud
  company.name: www.cxk.com
  build.artifactId: clouddo-zuul-6002
  build.version: 1.0-SNAPSHOT
